name: "Build"

on:
  pull_request:
    types: [ closed ]

jobs:  
  build:
    if: contains(github.event.pull_request.labels.*.name, 'release') && github.event.pull_request.merged == true
    name: Build & Release 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter --version

      - name: Decide Release Version
        run: |
          bash scripts/replace_version.sh
      
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
          
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties
        
      - name: Echo pubspec.yaml
        run: |
          cat pubspec.yaml

      - name: Build APK
        run: flutter build apk --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/app-release.apk
        
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v${{ env.VERSION }}
          
      - name: Install Tools
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Set up environment
        run: |
          echo "PUB_DATE=$(date -R)" >> $GITHUB_ENV
          echo "DOWNLOAD_URL$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.assets[0].browser_download_url')" >> $GITHUB_ENV
          echo "FILE_SIZE=$(curl -sI $DOWNLOAD_URL | grep -i Content-Length | awk '{print $2}' | tr -d '\r')" >> $GITHUB_ENV
          echo "APPCAST_URL=https://raw.githubusercontent.com/${{ github.repository }}/main/appcast.xml"
    
      - name: Generate appcast.xml
        run: |
          sed -e "s/{{APP_NAME}}/Landscape/g" \
              -e "s/{{VERSION}}/${{ env.VERSION }}/g" \
              -e "s/{{PUB_DATE}}/${{ env.PUB_DATE }}/g" \
              -e "s/{{CHANGELOG}}/${{ github.event.head_commit.message }}/g" \
              -e "s/{{DOWNLOAD_URL}}/${{ env.DOWNLOAD_URL }}/g" \
              -e "s/{{FILE_SIZE}}/${{ env.FILE_SIZE }}/g" \
              -e "s/{{APPCAST_URL}}/${{ env.APPCAST_URL }}/g"
              templates/appcast.xml > appcast.xml
      
      - name: Publish appcast
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "[KUROMESI-BOT] publish appcast.xml for v${{ env.VERSION }}"
          commit_options: '--signoff'
          commit_user_name: KUROMESI-BOT