name: "Build Test"

on:
  issue_comment:
    types: [ created ]

jobs:  
  build:
    if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/build-test')
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Decide Release Version
        run: |
          bash scripts/replace_version.sh

      - name: Echo pubspec.yaml
        run: |
          cat pubspec.yaml
          echo v${{ env.VERSION }}

      - name: Build APK
        run: flutter build apk --release