name: Pull Request (Opened)

on:
  pull_request:
    types: [opened]

jobs:
  security_hardening:
    name: Check security hardening
    runs-on: ubuntu-latest
    steps:
    - name: Clone the repository
      uses: actions/checkout@v4

  assign_author:
    name: Assign Author to the Pull Request
    needs: security_hardening
    runs-on: ubuntu-latest
    steps:
    - name: Assign Author to the Pull Request
      uses: technote-space/assign-author@v1

  pr-labeler:
    name: Label the PR based on the branch
    needs: security_hardening
    runs-on: ubuntu-latest
    steps:
    - name: Label the Pull Request
      uses: TimonVS/pr-labeler-action@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}